[package]
name = "cli_inventory_system"
version = "0.1.0"
edition = "2024"

[dependencies]
argon2 = "0.5.3"
rand = "0.8"
rand_core = { version = "0.9", features = ["os_rng"] }
serde = { version = "1.0.229", features = ["derive"] }

# serde_json is just for the example, not required in general
serde_json = "1.0"
validator = { version = "0.20", features = ["derive"] }
